### ISSUE TITLE
NOT AN ISSUE: battery wiring question

### ISSUE THREAD

**Issue by wesleywchang** [donus3/min34#1]
Not an issue, but I was wondering if you could share how you wired the batteries. I'm trying to build the wireless version of this board with the Xiao BLE. I don't have a background with electronics so it's a little confusing for me. Sharing images of how the battery is wired would be sufficient.

**Comment by donus3** [comment]
This is on my left

<img src="https://user-images.githubusercontent.com/9076885/207881847-365b94c4-ce5b-45cf-8860-977867cd0fc3.jpg" width="400" />
<img src="https://user-images.githubusercontent.com/9076885/207881883-9cd35361-1050-432f-83d4-d78749c19661.jpg" width="400" />

on my right switch will be placed on the top side of the PCB.

**Comment by wesleywchang** [comment]
I was able to get both halves powered wiring this way, but it looks like the power switch does nothing and the board is always powered. Is this the same case for you?

**Comment by donus3** [comment]
Mine work just fine. You can turn the switch on and put the usb c cable to the XIAO and notice if there is a yellow led turn on. if yes, you've already wire your controller to the PCB correctly. Then, you should check your battery soldering (black cable to the ground and red to the B+). You can post your build pictures here so I can help you validate.

**Comment by wesleywchang** [comment]
I was able to get the power switch working; I accidentally bridged the connection while soldering so the battery was in effect always connected. Thanks for the help! This is a really cool design and it's satisfying now that I've worked out all the kinks.
